#!/bin/sh
#
TEMP_D=""

cleanup() {
    [ -n "$TEMP_D" ] || return 0
    rm -Rf "$TEMP_D"
}

TEMP_D=$(mktemp -d)
trap cleanup EXIT

cd "$TEMP_D"

machine=$(uname -m)
arch=$machine
os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$machine" in
    aarch64) arch=arm64;;
esac

if false && [ -x "$HOME/bin/chainctl" ]; then
  chainctl update --yes
else
  url="https://dl.enforce.dev/chainctl/latest/chainctl_${os}_${arch}"
  curl -o chainctl "$url"
  install -m 0755 chainctl "$HOME/bin/"
fi

chainctl config set auth.device-flow chainguard
chainctl config set default.social-login google-oauth2
chainctl config set auth.mode headless

go install chainguard.dev/melange@latest
go install chainguard.dev/apko@latest
go install github.com/chainguard-dev/yam@latest

if ! command -v wolfictl >/dev/null 2>&1; then
    mkdir "$HOME/src"
    cd "$HOME/src"
    if [ ! -d wolfictl ]; then
        git clone -o upstream https://github.com/wolfi-dev/wolfictl
    fi
    cd wolfictl
    go install
fi

gists="
login-images:568f03b41efe80f57cea4605beec71ac
get-sbom:90730d2c62cb5a34adcaccf41d997d2b
wolfi-tools:0a11e2643b884960c1e5349d4dc0b8c7
"

mkdir -p "$HOME/gists"
cd "$HOME/gists"
burl=https://gist.github.com/smoser/
for gist in $gists; do
    name="${gist%:*}"
    hash=${gist#*:}
    if [ -d "$name" ]; then
        ( cd "$name"
          git fetch upstream
          git checkout upstream/main )
    else
        git clone -o upstream "$burl$hash" "$name"
    fi
done
