#!/bin/sh
[ "$(id -u)" = "0" ] || { echo "not root"; exit 1; }

mydir=${0%/*}
base=$( cd "$mydir/.." && echo "$PWD")
if [ -d "$base/bin" ]; then
    PATH="$base/bin:$PATH"
fi
export PATH

# sudo sysctl -w kernel.dmesg_restrict=0
v="kernel.dmesg_restrict = 0"
if sysctl kernel.dmesg_restrict | grep -q "$v"; then
    echo "dmesg_restrict already disabled"
else
    sysctl -w "$v"
    mkdir -p /etc/sysctl.d/
    printf "%s\n" "$v" > /etc/sysctl.d/99-dmesg.conf
    echo "dmesg_restrict disabled"
fi

if command -v apt-get; then
    "$mydir/system-debian" "$@"
elif command -v apk; then
    "$mydir/system-workstation" "$@"
else
    echo "FAIL: no system setup for your system"
    exit 1
fi
