#!/bin/sh
TEMP_D=""

pkgs="
tmux
cosign
vim
htop
less
patch
strace
parallel
qemu
petname
rsync
py3-ruamel-yaml
"
TEMP_D=$(mktemp -d)
trap cleanup EXIT

cd "$TEMP_D"

machine=$(uname -m)
arch=$machine
os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$machine" in
    aarch64) arch=arm64;;
esac

cleanup() {
    [ -n "$TEMP_D" ] || return 0
    rm -Rf "$TEMP_D"
}

timedatectl set-timezone US/Eastern
apk update
apk add $pkgs

chainctl update --yes

ln -sf vim /usr/bin/vi

mkdir /local-tmp && chmod 1777 /local-tmp

if ! command -v shellcheck; then
    scversion="v0.10.0"
    url="https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.$machine.tar.xz"
    echo "installing shellcheck $scversion for arch $machine from"
    echo "  $url"
    ( d=$(mktemp -d) &&
      trap "rm -Rf '$d'" EXIT &&
       dest="/usr/local/bin" &&
       cd "$d" && curl --fail -L "$url" > shellcheck.tar.xz &&
       tar -xf shellcheck.tar.xz &&
       rm -Rf "$dest/shellcheck" &&
       mkdir -p "$dest" &&
       sudo mv "shellcheck-$scversion/shellcheck" "$dest"
    )
fi
