#!/bin/sh
TEMP_D=""

pkgs="
argo-workflows-4.0
blkid
cosign
htop
inotify-tools
less
losetup
parallel
partx
patch
petname
py3-ruamel-yaml
qemu
rsync
sfdisk
strace
tmux
vim
xfsprogs-extra
"
TEMP_D=$(mktemp -d)
trap cleanup EXIT

cd "$TEMP_D"

machine=$(uname -m)
arch=$machine
os=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$machine" in
    aarch64) arch=arm64;;
esac

cleanup() {
    [ -n "$TEMP_D" ] || return 0
    rm -Rf "$TEMP_D"
}

timedatectl set-timezone US/Eastern
apk update
apk add $pkgs

chainctl update --yes

ln -sf vim /usr/bin/vi

mkdir -p /local-tmp && chmod 1777 /local-tmp
